### ISSUE TITLE
Weather not showing up on multi-page presentations

### ISSUE THREAD

**Issue by dlugo00** [Rise-Vision/widget-weather#11]
Weather will not show up on multi page presentations. If created globally then it will show up fine but as soon as you move weather div into a specific page the weather disappears. 

The only work around is to display today's current weather only and the placeholder has to be sized properly. If the placeholder is too large the the weather image will disappear.

- Presentation Examples: http://rva.risevision.com/#PRESENTATION_MANAGE/id=1df36bab-26e9-4e32-9362-08d03047c92b/company=dc1e2ddf-e874-402d-888b-5e5f88b4780b
- Video Overview: http://www.screencast.com/t/gVC7RdupV6V

**Comment by donnapep** [comment]
@dlugo00 This is fixed after rewriting the Weather Widget settings to Angular:
Settings URL - http://s3.amazonaws.com/widget-weather-test/0.1.0/dist/settings.html
Widget URL - http://s3.amazonaws.com/widget-weather-test/0.1.0/dist/current.html

**Comment by dlugo00** [comment]
@donnapep Can you clarify, has this fix been deployed?

**Comment by donnapep** [comment]
@dlugo00 No, it needs to be tested first.

**Comment by donnapep** [comment]
@dlugo00 I mentioned it in the Release Notes on this card - http://goo.gl/cH3tsO - but perhaps you also want to test it seperately? Thx.

**Comment by dlugo00** [comment]
@donnapep Ok perfect! It looks like Justin and Robb will be taking care of it. Thanks.

**Comment by justinsmith1** [comment]
@donnapep @dlugo00 I made a copy of the presentation that David linked above, and added the test Weather Widget to it, and weather is appearing fine.
