### ISSUE TITLE
3 day weather forecast shows low/hi when it should show hi/low

### ISSUE THREAD

**Issue by dlugo00** [Rise-Vision/widget-weather#12]
The 3 day forecast shows the highs and lows in this format -> low/high rather then it this format-> high/low. The forecast should show the Highs first and then the Lows.

**Comment by donnapep** [comment]
@dlugo00 This is fixed after rewriting the Weather Widget settings to Angular:
Settings URL - http://s3.amazonaws.com/widget-weather-test/0.1.0/dist/settings.html
Widget URL - http://s3.amazonaws.com/widget-weather-test/0.1.0/dist/current.html
