### ISSUE TITLE
Font or Font Size drop-down lists open and close immediately when you click on them

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/widget-weather#14]
In the Widget configuration, wherever there is a font-list selection, or font size selection, clicking once opens the list but then the list disappears immediately when you take your finger off the mouse.  If you click and hold the list will stay open.

It happens with all these lists:
- Current Temperature Font and Current Temperature Font Size
- Forecast Temperature Font and Forecast Temperature Font Size
- Forecast Day Font and Forecast Day Font Size
- Address Font and Font Size
- Wind Speed Font and Font Size

**Comment by donnapep** [comment]
@alanclayton @AlexKolenoff This is fixed after rewriting the Weather Widget settings to Angular:
Settings URL - http://s3.amazonaws.com/widget-weather-test/0.1.0/dist/settings.html
Widget URL - http://s3.amazonaws.com/widget-weather-test/0.1.0/dist/current.html

**Comment by AlexKolenoff** [comment]
The drop-downs work as expected now.

**Comment by justinsmith1** [comment]
@AlexKolenoff @donnapep confirmed. Looks good now.
