### ISSUE TITLE
Right Click menu comes up when you hold your finger down on a touchscreen using Native Windows Player (2.0.035)

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-weather#2]
What steps will reproduce the problem?
1. Add the Gadget to your Presentation.
2. When it is running on a Display, hold your finger on the Gadget, notice that the Right Click options appear.

What is the expected output? What do you see instead?
The right click menu should not come up.

**Comment by donnapep** [comment]
Investigated but haven't found a way to do this so far.

**Comment by alanclayton** [comment]
@donnapep I don't think this is worth investigating.

**Comment by donnapep** [comment]
@alanclayton OK, does that mean this can be closed?

**Comment by alanclayton** [comment]
@donnapep Yep.
