### ISSUE TITLE
Weather auto-resize is not functioning as intended.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-weather#24]
Steps to reproduce:
1. Create a placeholder with a height of 275 pixels or less.
2. Add weather widget to placeholder

Result:
The weather widget appears with the text cut off.

How it should work:
The weather widget should automatically resize it's images and fonts to be responsive to any resolution.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=a9cdbad0-018b-487b-8036-08623d273445

OS:
OS X

Chrome Ver:
41.0.2272.104

**Comment by ByronDarlison** [comment]
@alanclayton what's your take on this? Should we fix or move to address with 3rd party content? Thanks

**Comment by alanclayton** [comment]
@ByronDarlison we should address it with a 3rd party developer. @btfrise can you test to see if this is an issue with this Widget https://store.risevision.com/#/product/54/weather-forecast-and-conditions and let me know the results?

**Comment by btfrise** [comment]
@alanclayton That widget has the same issue, preview here - http://preview.risevision.com/Viewer.html?type=presentation&id=a9cdbad0-018b-487b-8036-08623d273445

**Comment by alanclayton** [comment]
@btfrise Thanks. @robb-price when you preview the digi weather can you provide the above scenario as feedback for improvement to digi?

**Comment by robb-price** [comment]
@alanclayton Will do.

**Comment by btfrise** [comment]
@alanclayton @robb-price Is digichief going to move forward with this? Should I close this issue?

**Comment by robb-price** [comment]
@btfrise I'll bring this up to Gene to find out. Once I know, I'll update the issue accordingly.

**Comment by robb-price** [comment]
@alanclayton @btfrise Gene is planning to fix this in his Widget. I will make sure to test this when testing their Widget. I think we can close this issue unless there are any disagreements.

**Comment by btfrise** [comment]
@robb-price Thanks, I'll close.
