### ISSUE TITLE
Weather widget doesn't work with geolocation and the notice isn't visible on initial set up.

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/widget-weather#26]
### Initial set up:
![weather](https://cloud.githubusercontent.com/assets/1511535/21864821/886eecae-d811-11e6-9d39-179b9aa84dc1.png)

### Editing once placed in a placeholder:
![weather2](https://cloud.githubusercontent.com/assets/1511535/21864876/b0205b98-d811-11e6-93c9-2ac092ba5b11.png)

**Comment by robb-price** [comment]
Not pursuing this right now. Closing.
