### ISSUE TITLE
Get display address does not work

### ISSUE THREAD

**Issue by xelio91** [Rise-Vision/widget-weather#27]
Hello,
If I set "Display Address" it doesn't work at all. It works if I setup any specific location..
I actually don't know if I get error in the widget or setting an incorrect address in display settings. Of course I tried to set the address in many ways but nothing change.

**Comment by stulees** [comment]
@xelio91 Thanks for reporting this. We've looked into the issue and there is indeed a bug in the code  that is preventing the use of "Display Address" to work properly. However, this Widget has been deprecated for some time and we no longer maintain this source code.

We recommend using any of the following Weather Widgets from the Rise Vision store here - https://store.risevision.com/products/?q=weather&cat=Content
