### ISSUE TITLE
Some Custom address locations with accented letters will show up with ?

### ISSUE THREAD

**Issue by nealg1** [Rise-Vision/widget-weather#4]
Using this Presentation: http://rva.risevision.com/?parentId=feeb43c6-2d4a-4ea6-9f8c-bf1c896a7fa9#PRESENTATION_MANAGE/id=6eddb7c7-e21d-4fd0-8eae-172aa50c0f6e/company=d94a0813-305e-4190-81e4-314d20712487

Notice that the first Weather item in the ph0 Placeholder has a custom location set.  This location shows as Noum?a on the Display.

**Comment by donnapep** [comment]
@nealg1 @alanclayton I checked this on a Chrome App player on Windows and wasn't able to reproduce. Please check to see if this can be closed. Thx.

**Comment by donnapep** [comment]
Correction, I checked on a Windows player and it's working there. Thx.

**Comment by alanclayton** [comment]
Won't fix. Closing issue.
